### ISSUE TITLE
Publish the demo as GH pages?

### ISSUE THREAD

**Issue by kinow** [PauloMigAlmeida/directed-acyclic-graph-builder-js#2]
It'd be nice to have the application from `demo/` published to the `gh-pages` branch (with `ghp-import`, or some GH Actions, for instance). That way we could try it without having to build it locally :+1: 

Thanks!
Bruno

**Comment by PauloMigAlmeida** [comment]
Great idea! Will start working on it now 👍🏻

**Comment by PauloMigAlmeida** [comment]
@kinow here it goes: https://paulomigalmeida.github.io/directed-acyclic-graph-builder-js/demo/static/index.html

**Comment by kinow** [comment]
Hooray! The demo is accessible now, but I'm now getting the same error as #1 GIF to demonstrate it:

![GIFrecord_2022-09-06_224602](https://user-images.githubusercontent.com/304786/188620566-9d1fe83c-4486-4732-ad88-b86ced9888d4.gif)

I'm using Ubuntu LTS' Firefox, version 104.0.1 (64-bit), same error with Chromium Version 105.0.5195.52 (Official Build) snap (64-bit).

**Comment by kinow** [comment]
Closing this one as the demo is now published :+1: Thanks Paulo!

**Comment by kinow** [comment]
p.s. I saw the demo URL in the README, thanks! I think now the demo URL can be used as the URL for this repository. Somewhere in the settings for this project, or in the landing page (maybe to the right of the screen?) you should find a place to define the URL.

**Comment by PauloMigAlmeida** [comment]
Nice, didn't know that. Just did it :) Thanks heaps mate
